print("введите тип животного")
Type = input()
print("введите возраст животного")
Age = input()
print("введите кличку животного")
Name = input()
print("Это", Type, "по кличке", Name + '.', "Возраст:", Age, "лет.")
